[package]
name = "kcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.28"
nix = { version = "0.27.1", features = ["feature"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.50"
toml = "0.8.6"
