name: Rust

on:
  push:
    branches: [ "main", "jds/*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format Check
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build --verbose --release